### PR TITLE
Update 1.index.md

### PR DESCRIPTION
**Pull request by mikehappythoughts**
Hi Guys just want to say great job on the nuxt Tailwind docs. I noticed a grammer mistake in your docs. See below:

**THis module help** you setup Tailwind CSS (version 2) to your Nuxt application in seconds.

 I have submitted this pull request to correct the above mistake. I look forward to your review.

Regards Mike :)

### CODE REVIEW

**Review by w3bdesign — APPROVED** [review]

**Review by w3bdesign — CHANGES_REQUESTED** [review]
Hi @mikehappythoughts 

Your commit should be semantically versioned. Right now it is not.

Take a look at https://github.com/zeke/semantic-pull-requests

**Comment by mikehappythoughts** [comment]
> Hi @mikehappythoughts
> 
> Your commit should be semantically versioned. Right now it is not.
> 
> Take a look at https://github.com/zeke/semantic-pull-requests


Hi @w3bdesign
I have added semantic-pull-requests action to my fork of your repository. I am new to this and wondered how do I change my original pull request or do I resubmit it again. Any help to get this corrected is appreciated. Have a good day.

**Comment by w3bdesign** [comment]
> 
> 
> > Hi @mikehappythoughts
> > Your commit should be semantically versioned. Right now it is not.
> > Take a look at https://github.com/zeke/semantic-pull-requests
> 
> Hi @w3bdesign
> I have added semantic-pull-requests action to my fork of your repository. I am new to this and wondered how do I change my original pull request or do I resubmit it again. Any help to get this corrected is appreciated. Have a good day.

@mikehappythoughts 
I just closed it and reopened a new one.

**Comment by w3bdesign** [comment]
@mikehappythoughts 

You can see how I did it here:

https://github.com/nuxt-community/tailwindcss-module/pull/306

**Comment by mikehappythoughts** [comment]
> @mikehappythoughts
> 
> You can see how I did it here:
> 
> #306

Hi @w3bdesign,
Does that mean this pull request is now merged and I do not need to do anything else? Or do I need to still something my side to get things resolved? Sorry about the questions as I know you are busy. But just want to make sure things are done right.

**Comment by w3bdesign** [comment]
> 
> 
> > @mikehappythoughts
> > You can see how I did it here:
> > #306
> 
> Hi @w3bdesign,
> Does that mean this pull request is now merged and I do not need to do anything else? Or do I need to still something my side to get things resolved? Sorry about the questions as I know you are busy. But just want to make sure things are done right.

@mikehappythoughts 

1. Click "Close pull request"
2. Click "Delete branch" / or manually delete the forked repository
3. Recreate the change in this repository with the semantically correct syntax (see my PR if you are unsure on how to do it. Basically you just put `docs: my message` in the title)
4. Ask me if you are still stuck

**Comment by mikehappythoughts** [comment]
Hi @w3bdesign,
Thanks for your help I really appreciate it. I will sort now. I have one last question where would I find the close pull request as I cannot see any pull requests in the repo I forked from your repo.

**Comment by w3bdesign** [comment]
> 
> 
> Hi @w3bdesign,
> Thanks for your help I really appreciate it. I will sort now. I have one last question where would I find the close pull request as I cannot see any pull requests in the repo I forked from your repo.

@mikehappythoughts 

You need to fork this repo (https://github.com/nuxt-community/tailwindcss-module), not my repo.

**Comment by mikehappythoughts** [comment]
Hi @w3bdesign,
That is the one  forked.

**Comment by w3bdesign** [comment]
> 
> 
> Hi @w3bdesign,
> That is the one forked.

@mikehappythoughts 

You may have to delete your fork.

The easiest way is to modify the README.md in this repo.

**Comment by mikehappythoughts** [comment]
Hi @w3bdesign,
Thanks for all your help but even though I changed the title to doc: corrected minor typo  it still did not go through said that the current head and my pull request head differs. And this was from a fresh fork of the nuxt-community repo. So I am going to leave it. I have closed my pull requests. Thanks again for the assist really appreciated. Have a good one.

**Pull request closed without merging**
