### PR TITLE
fix(module): Nuxt 2 support

### PR DESCRIPTION
**Pull request by Tahul**
Since 5.2.0, some Nuxt 2 users encountered issues with the module.

@bmulholland kindly found it was related to `@nuxt/kit` inconsistencies between Nuxt 2 and 3.

That PR solves the support for tailwind.config in Nuxt 2, and disables the config viewer in that environment.

Config viewer seem to break the stack as @nuxt/kit `addServerHandler` seem to break the module in that environment.

That issue is tracked here, thanks to @harlan-zw: https://github.com/nuxt-community/tailwindcss-module/issues/507

Resolves: #500

### CODE REVIEW

**Comment by Tahul** [comment]
Hey @bmulholland ;

If you want to use the fix in your app, I made an edge publish for it:
`@nuxtjs/tailwindcss-edge@5.3.0-a9077c2`

Thanks for your collaboration and sorry for not checking Nuxt 2 support earlier, it was unexpected!

**Comment by harlan-zw** [comment]
Looks good :+1:  The Nuxt 2 playground will be useful to avoid regressions in the future

**Comment by dneckel** [comment]
Would love to see this merged soon ❤️

**Review by Atinux — APPROVED** [review]

**Comment by pencilcheck** [comment]
Not sure if this is related, but I am also getting this error when I tried to add it as a module inside my builder class

https://github.com/nuxt-modules/tailwindcss/issues/505

https://github.com/nuxt/nuxt.js/discussions/10247

**Pull request merged**
