### PR TITLE
feat!: v4

### PR DESCRIPTION
**Pull request by pi0**
- Tailwindcss2 
  - [x] Basic Upgrade (https://github.com/nuxt-community/tailwindcss-module/pull/270 by @RomainLan)
  - [x] Postcss8 compatibility (https://github.com/nuxt/postcss8) 
- [x] Update documentation 
- [x] Typescript rewrite
- [x] ~~Fix~~ update tests
- [x] Cleanup branch

Next version is currently available as `@nuxtjs/tailwindcss@alpha` (4.x)

### CODE REVIEW

**Comment by productfrontenddeveloper** [comment]
new update 40 minutes ago [tailwindcss-jit 0.1.0](https://github.com/tailwindlabs/tailwindcss-jit/releases/tag/v0.1.0)

**Comment by productfrontenddeveloper** [comment]
```@nuxtjs/tailwindcss@alpha``` and ```@nuxt/postcss8```  install 

```
in ./layouts/auth.vue?vue&type=style&index=0&id=176a1cfc&scoped=true&lang=scss& (./node_modules/@nuxt/postcss8/node_modules/css-loader/dist/cjs.js??ref--7-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/@nuxt/postcss8/node_modules/postcss-loader/dist/cjs.js??ref--7-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--7-oneOf-1-3!./node_modules/vue-loader/lib??vue-loader-options!./layouts/auth.vue?vue&type=style&index=0&id=176a1cfc&scoped=true&lang=scss&)
Module build failed (from ./node_modules/@nuxt/postcss8/node_modules/postcss-loader/dist/cjs.js):
TypeError: getProcessedPlugins is not a function
``` 

auth.vue
```
<style scoped lang="scss">
.body {
  @apply bg-gray-100;
}
</style>
```

**Comment by Atinux** [comment]
@productfrontenddeveloper please install `@nuxtjs/tailwindcss@alpha postcss@latest`

**Comment by productfrontenddeveloper** [comment]
> @productfrontenddeveloper please install `@nuxtjs/tailwindcss@alpha postcss@latest`

Thank you, Everything is working well. No change in speed, is that normal ?

**Comment by eggsy** [comment]
Doesn't seem like it's really building Tailwind classes for me, no errors, tried `yarn upgrade`, tried in production, tried removing custom config, used the default Tailwind config options, didn't work.

image

**Comment by Atinux** [comment]
@eggsy make sure to `yarn add --dev @nuxtjs/tailwindcss@alpha`

**Comment by eggsy** [comment]
> @eggsy make sure to `yarn add --dev @nuxtjs/tailwindcss@alpha`

Yep, it's all in the right place but still doesn't work. I have a separate source directory, could it be that? Maybe PostCSS isn't looking for the right paths.

image

**Pull request merged**
