### PR TITLE
fix: tailwind viewer url

### PR DESCRIPTION
**Pull request by shba007**
The tailwind viewer url is showing only "/_tailwind/" missing the rest of the url.

### CODE REVIEW

**Comment by Atinux** [comment]
Hi @shba007 

Can you review you change to avoid adding the comma please?

**Comment by shba007** [comment]
Sorry for the auto format I reverted to previous format...please check

**Comment by shba007** [comment]
Can you tell me which variable holds the port? Example if nuxt runs on http://localhost:4321 which variable holds the 4321 port or something like that?

**Comment by Atinux** [comment]
Thanks 💚

**Pull request merged**
