### PR TITLE
chore(deps): Update tailwind to 2.1 to natively support JIT

### PR DESCRIPTION
**Pull request by RomainMazB**
Hi there!

TailwindCSS team added the JIT mode to the core!

Some issues could probably resolve itself if we stop using the additional jit true/false config and let the process be more fluid #299, #298, #302 .

Since the JIT mode needs "a basic" purge config for now (an array referring files to watch instead of a object containing a content property), I also updated the documentation to make it clear that we need to override the default nuxtjs-tailwind purge config from this:
```js
export default ({ _dev, rootDir, srcDir }) => ({
  purge: {
    content: [
      `${srcDir}/components/**/*.{vue,js}`,
      `${srcDir}/layouts/**/*.vue`,
      `${srcDir}/pages/**/*.vue`,
      `${srcDir}/plugins/**/*.{js,ts}`,
      `${rootDir}/nuxt.config.{js,ts}`
    ],
    // https://tailwindcss.com/docs/optimizing-for-production#purge-css-options
    options: {}
  }
```
to this:
```js
export default {
  mode: 'jit',
  purge: [
    `~/components/**/*.{vue,js}`,
    `~/layouts/**/*.vue`,
    `~/pages/**/*.vue`,
    `~/plugins/**/*.{js,ts}`,
    `~~/nuxt.config.{js,ts}`
  ]
}
```

I would like to add some test for this, but I'm not so comfortable with Jest to analyze the javascript compilated file to expect the `top-[12px]` class to be present in it.

### CODE REVIEW

**Review by viennv1709 — CHANGES_REQUESTED** [review]
Update `src\index.ts` to reflect changes

**Comment by RomainMazB** [comment]
@Atinux
Why this isn't merged yet? I'm not sure if some extra-work should be done from my side, I don't see any review to validate or what so ever but both git and NodeJS/TS are my friend.

**Comment by Atinux** [comment]
Updated and merged, thank you very much ❤️

**Comment by Stun3R** [comment]
Hi,

Maybe we should removed the dependency `"@tailwindcss/jit":"^0.1.18"` since it's no longer needed and has not been removed from the package.json.

**Pull request merged**
