### PR TITLE
docs: update nuxt 2.15 & tailwindcss 2.x with typography & dark-mode example

### PR DESCRIPTION
**Pull request by vinayakkulkarni**
- [x] TailwindCSS 2.x out of the box! 🎉
- [x] Update contributors to be more verbose
- [x] Refactor the docs to use `docus.dev` instead of `nuxt content / theme docs`
- [x] Add example of using [tailwindui](https://tailwindcss.nuxtjs.org/examples/tailwind2) with Tailwind CSS 2.x

### CODE REVIEW

**Comment by vinayakkulkarni** [comment]
> Hi @vinayakkulkarni
> 
> Thank you for the PR, I am not sure that these plugins should be implemented directly into the module, but instead being documented (like the example you added).

I'll update the PR

**Comment by vinayakkulkarni** [comment]
🛎 @Atinux

**Comment by vinayakkulkarni** [comment]
If you merge this branch @Atinux, all your conflicts will be gone in #203

**Comment by vinayakkulkarni** [comment]
I rebased my branch with `upstream/master` so that when you're merging your PR to `master`, you won't get any conflicts

**Comment by Atinux** [comment]
Sorry @vinayakkulkarni, plenty of changes on this module, all have been updated to use latest Tailwind 😊 

Thank you again for your help!

**Pull request closed without merging**
